spring:
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/hr-worker/**
    loadbalancer:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
  
    
    